### ISSUE TITLE
About terror tree

### ISSUE THREAD

**Issue by Paloras** [BraINstinct0/CodeStash#2]
please delete that repo

**Comment by BraINstinct0** [comment]
Pardon?

**Comment by Paloras** [comment]
Can you delete the terror_tree repogistory? 
https://github.com/BraINstinct0/terror_tree

**Comment by BraINstinct0** [comment]
Ah, sure! Seems like the original one was deleted, so I'll close the issue here!

**Comment by BraINstinct0** [comment]
Done!
